import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import { AppProviders } from './providers';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-[100vw]">
        <AppProviders>
          <Navbar/>
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
